# What to call your wiki.
name: My Wiki Name

# Description for HTML metadata.
description: A wiki.

# Who can sign up for accounts? (private or public)
access: public

# Colour of the interface.
primary_color: "#A80A00"

# Sidebar primary icon. Must be a Font Awesome icon.
primary_icon: dragon

# (Optional) Github url of your hack.
github_url: https://github.com/tipsypastels/pokegnosis